# Generated by Django 5.0.2 on 2024-02-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskTitle', models.CharField(max_length=20)),
                ('taskDescription', models.CharField(max_length=30)),
                ('is_completed', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
